import type {
  WorkItem,
  WorkTabItem,
} from '@/features/logged/dashboard/types/work-list'

export const WORK_TEST_DEPARTURE_CODE = 'EM-b3'

export const WORK_TEST_DESTINATION_CODE = 'N1-b1'

export const WORK_LIST_TABS: WorkTabItem[] = [
  { key: 'all', label: '전체', count: 10 },
  { key: 'pending', label: '대기', count: 4 },
  { key: 'complete', label: '완료', count: 6 },
]

export const WORK_ITEMS: WorkItem[] = [
  {
    id: 15601,
    status: 'pending',
    activityCode: '2371S515AS10S10',
    stage: '소조립',
    hullNo: '2371',
    blockNo: '515',
    pcg: 'CMR',
    departureCode: WORK_TEST_DEPARTURE_CODE,
    departureName: '기자재공장',
    arrivalCode: WORK_TEST_DESTINATION_CODE,
    arrivalName: '내업1공장',
    detail: {
      startedAt: '2026/05/20',
      completedAt: '2026/05/20',
      description: '블록 이동 작업',
    },
  },
  {
    id: 15600,
    status: 'pending',
    activityCode: '2371S517AM10M10',
    stage: '중조립',
    hullNo: '2371',
    blockNo: '517',
    pcg: 'CMR',
    departureCode: 'EM-b1',
    departureName: '기자재공장',
    arrivalCode: 'O2-b2',
    arrivalName: '외업2작업장',
  },
  {
    id: 15599,
    status: 'pending',
    activityCode: '2539WH40EA10F1O',
    stage: '전장',
    hullNo: '2539',
    blockNo: 'H40',
    pcg: 'P/Mast',
    departureCode: 'EM-b1',
    departureName: '기자재공장',
    arrivalCode: 'O2-b3',
    arrivalName: '외업2작업장',
  },
  {
    id: 15598,
    status: 'pending',
    activityCode: '2580P40BRP10P10',
    stage: 'PE도장',
    hullNo: '2580',
    blockNo: '40B',
    pcg: 'LNGC TBHD',
    departureCode: 'E1-b1',
    departureName: 'PE1장',
    arrivalCode: 'PS-p4',
    arrivalName: '도장공장',
  },
  {
    id: 15597,
    status: 'complete',
    activityCode: '2371S519BM10M10',
    stage: '중조립',
    hullNo: '2371',
    blockNo: '519',
    pcg: 'CMR',
    departureCode: 'N1-b4',
    departureName: '내업1공장',
    arrivalCode: 'O2-b2',
    arrivalName: '외업2작업장',
  },
  {
    id: 15596,
    status: 'complete',
    activityCode: '2539WH42EA10F1O',
    stage: '전장',
    hullNo: '2539',
    blockNo: 'H42',
    pcg: 'P/Mast',
    departureCode: 'EM-b1',
    departureName: '기자재공장',
    arrivalCode: 'O2-b3',
    arrivalName: '외업2작업장',
  },
  {
    id: 15595,
    status: 'complete',
    activityCode: '2580P41BRP10P10',
    stage: 'PE도장',
    hullNo: '2580',
    blockNo: '41B',
    pcg: 'LNGC TBHD',
    departureCode: 'E1-b1',
    departureName: 'PE1장',
    arrivalCode: 'PS-p4',
    arrivalName: '도장공장',
  },
  {
    id: 15594,
    status: 'complete',
    activityCode: '2371S521CL10L10',
    stage: '대조립',
    hullNo: '2371',
    blockNo: '521',
    pcg: 'CMR',
    departureCode: 'O2-b2',
    departureName: '외업2작업장',
    arrivalCode: 'E1-b1',
    arrivalName: 'PE1장',
  },
  {
    id: 15593,
    status: 'complete',
    activityCode: '2539WH43FA10F1O',
    stage: '선행의장',
    hullNo: '2539',
    blockNo: 'H43',
    pcg: 'P/Mast',
    departureCode: 'F1-b1',
    departureName: '선행의장공장',
    arrivalCode: 'E1-b1',
    arrivalName: 'PE1장',
  },
  {
    id: 15592,
    status: 'complete',
    activityCode: '2580P42BTP10T10',
    stage: '도장',
    hullNo: '2580',
    blockNo: '42B',
    pcg: 'LNGC TBHD',
    departureCode: 'PS-p4',
    departureName: '도장공장',
    arrivalCode: 'N1-b4',
    arrivalName: '내업1공장',
  },
]
