import type {
  WorkItem,
  WorkTabItem,
} from '@/features/logged/dashboard/types/work-list'

export const WORK_LIST_TABS: WorkTabItem[] = [
  { key: 'all', label: '전체', count: 10 },
  { key: 'pending', label: '대기', count: 4 },
  { key: 'complete', label: '완료', count: 6 },
]

export const WORK_ITEMS: WorkItem[] = [
  {
    id: 15601,
    status: 'pending',
    category: '블록 이동',
    objectCode: 'BT001',
    objectName: '함수',
    departureCode: 'AA1001',
    departureName: '의장재 공장',
    detail: {
      weightTons: 10,
      dimensions: '10*20*10',
      startedAt: '2026/05/20',
      completedAt: '2026/05/20',
      description: '블록 불출작업을 위한 주변 블록 이동 작업',
    },
  },
  {
    id: 15600,
    status: 'pending',
    category: '자재 이동',
    objectCode: 'ZG001',
    objectName: 'Volt',
    departureCode: 'AC2010',
    departureName: '의장재 적치장',
  },
  {
    id: 15599,
    status: 'pending',
    category: '자재 이동',
    objectCode: 'ZG009',
    objectName: 'Nut',
    departureCode: 'AA1002',
    departureName: '의장재 적치장',
  },
  {
    id: 15598,
    status: 'pending',
    category: '자재 이동',
    objectCode: 'ZG102',
    objectName: '강재',
    departureCode: 'AA1001',
    departureName: '강재물류센터',
  },
  {
    id: 15597,
    status: 'complete',
    category: '블록 이동',
    objectCode: 'BT017',
    objectName: '선미',
    departureCode: 'AA1002',
    departureName: '외업 1작업장',
  },
  {
    id: 15596,
    status: 'complete',
    category: '자재 이동',
    objectCode: 'ZG114',
    objectName: '강판',
    departureCode: 'AC2010',
    departureName: '의장재 적치장',
  },
  {
    id: 15595,
    status: 'complete',
    category: '자재 이동',
    objectCode: 'ZG125',
    objectName: '파이프',
    departureCode: 'AA1001',
    departureName: '강재물류센터',
  },
  {
    id: 15594,
    status: 'complete',
    category: '블록 이동',
    objectCode: 'BT021',
    objectName: '갑판',
    departureCode: 'AA1002',
    departureName: '외업 1작업장',
  },
  {
    id: 15593,
    status: 'complete',
    category: '자재 이동',
    objectCode: 'ZG131',
    objectName: '밸브',
    departureCode: 'AC2010',
    departureName: '기자재공장',
  },
  {
    id: 15592,
    status: 'complete',
    category: '자재 이동',
    objectCode: 'ZG145',
    objectName: '볼트',
    departureCode: 'AA1001',
    departureName: '의장재 공장',
  },
]
